"""LaTeX and PDF output helpers."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from .model import Model
from .operators import Lagrangian
from .latex_display import render_display_equations

def _display_equations(body: str) -> str:
    return render_display_equations(body, separator=" " + "\\" + "\n")



def _latex_escape_text(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _title_block(title: str) -> str:
    safe_title = _latex_escape_text(title)
    return rf"""
\begin{{center}}
{{\LARGE \bfseries {safe_title} \par}}
\vspace{{0.35em}}
{{\large Lagrangian Report \par}}
\vspace{{0.7em}}
\fcolorbox{{black}}{{gray!10}}{{\textsf{{\small Generated by bsm\_agent || Shaikh Saad}}}}
\end{{center}}
\vspace{{1em}}
"""


def latex_document(
    lagrangian: Lagrangian,
    *,
    title: str = "bsm_agent Lagrangian",
    model: Model | None = None,
    ewsb: bool | dict | None = None,
) -> str:
    compact = lagrangian.latex()
    expanded = lagrangian.expanded_latex(categories=["scalar_potential"])
    ewsb_body = ""
    if ewsb is not None:
        if model is None:
            raise ValueError("`model` is required when requesting EWSB LaTeX output")
        from .agent_backend import _ewsb_report_section, _normalize_ewsb_config

        ewsb_config = _normalize_ewsb_config(ewsb)
        if ewsb_config is not None:
            ewsb_section = _ewsb_report_section(model, lagrangian, ewsb_config)
            if ewsb_section is not None:
                ewsb_body = rf"""
\section{{EWSB Mass Matrices}}
{ewsb_section}
"""
    return rf"""\documentclass[11pt]{{article}}
\usepackage[a4paper,margin=1in]{{geometry}}
\usepackage{{amsmath,amssymb}}
\usepackage{{xcolor}}
\usepackage{{breqn}}
\usepackage[colorlinks=true,linkcolor=blue,urlcolor=blue]{{hyperref}}
\begin{{document}}
{_title_block(title)}
\tableofcontents
\bigskip

\section{{Compact Lagrangian}}
{_display_equations(compact)}

\section{{Expanded Scalar Potential}}
{_display_equations(expanded)}

{ewsb_body}

\end{{document}}
"""


def write_latex(
    lagrangian: Lagrangian,
    path: str | Path,
    *,
    title: str = "bsm_agent Lagrangian",
    model: Model | None = None,
    ewsb: bool | dict | None = None,
) -> Path:
    target = Path(path)
    target.write_text(latex_document(lagrangian, title=title, model=model, ewsb=ewsb))
    return target


def write_pdf(
    lagrangian: Lagrangian,
    path: str | Path,
    *,
    title: str = "bsm_agent Lagrangian",
    model: Model | None = None,
    ewsb: bool | dict | None = None,
) -> Path:
    """Write a PDF using pdflatex.

    Raises ``RuntimeError`` if pdflatex is not installed.
    """

    target = Path(path)
    if target.suffix != ".pdf":
        raise ValueError("PDF output path must end in .pdf")
    if shutil.which("pdflatex") is None:
        raise RuntimeError("pdflatex is not installed or not on PATH")

    tex_path = target.with_suffix(".tex")
    write_latex(lagrangian, tex_path, title=title, model=model, ewsb=ewsb)
    for _ in range(2):
        subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", tex_path.name],
            cwd=tex_path.parent or Path("."),
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    produced = tex_path.with_suffix(".pdf")
    if produced != target:
        produced.replace(target)
    return target
